### ISSUE TITLE
Documentation doesn't build

### ISSUE THREAD

**Issue by martinholters** [JuliaDSP/DSP.jl#182]
From the readthedocs build log:
```
Running Sphinx v1.5.3
making output directory...
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dspjl/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dspjl/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dspjl/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 523, in setup_extension
    ext_meta = mod.setup(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dspjl/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/mathjax.py", line 72, in setup
    raise ExtensionError('sphinx.ext.mathjax: other math package is already loaded')
ExtensionError: sphinx.ext.mathjax: other math package is already loaded

Extension error:
sphinx.ext.mathjax: other math package is already loaded
```

Maybe instead of fixing this, it's time to move to Documenter.jl?

**Comment by ararslan** [comment]
+1 for Documenter.

**Comment by martinholters** [comment]
I'll start porting things over, but it might be a few days...
